-- CreateTable
CREATE TABLE "receipt_templates" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'KITCHEN',
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "showLogo" BOOLEAN NOT NULL DEFAULT false,
    "logoUrl" TEXT,
    "logoAlignment" TEXT NOT NULL DEFAULT 'center',
    "logoWidth" INTEGER NOT NULL DEFAULT 48,
    "showBusinessName" BOOLEAN NOT NULL DEFAULT true,
    "businessName" TEXT NOT NULL DEFAULT 'KING FOOD',
    "showPhone" BOOLEAN NOT NULL DEFAULT false,
    "phone" TEXT,
    "showAddress" BOOLEAN NOT NULL DEFAULT false,
    "address" TEXT,
    "showInstagram" BOOLEAN NOT NULL DEFAULT false,
    "instagram" TEXT,
    "showOrderNumber" BOOLEAN NOT NULL DEFAULT true,
    "showDateTime" BOOLEAN NOT NULL DEFAULT true,
    "showOrderType" BOOLEAN NOT NULL DEFAULT true,
    "showCustomer" BOOLEAN NOT NULL DEFAULT false,
    "showCustomerPhone" BOOLEAN NOT NULL DEFAULT false,
    "showDeliveryAddress" BOOLEAN NOT NULL DEFAULT false,
    "showNotes" BOOLEAN NOT NULL DEFAULT true,
    "showQuantity" BOOLEAN NOT NULL DEFAULT true,
    "showItemName" BOOLEAN NOT NULL DEFAULT true,
    "showModifiers" BOOLEAN NOT NULL DEFAULT true,
    "showPrices" BOOLEAN NOT NULL DEFAULT false,
    "showSubtotal" BOOLEAN NOT NULL DEFAULT false,
    "showDeliveryFee" BOOLEAN NOT NULL DEFAULT false,
    "showDiscount" BOOLEAN NOT NULL DEFAULT false,
    "showTax" BOOLEAN NOT NULL DEFAULT false,
    "showTotal" BOOLEAN NOT NULL DEFAULT true,
    "showPaymentMethod" BOOLEAN NOT NULL DEFAULT false,
    "showFooter" BOOLEAN NOT NULL DEFAULT false,
    "footerText" TEXT,
    "footerAlignment" TEXT NOT NULL DEFAULT 'center',
    "separatorStyle" TEXT NOT NULL DEFAULT 'dashes',
    "fontSize" TEXT NOT NULL DEFAULT 'medium',
    "boldBusinessName" BOOLEAN NOT NULL DEFAULT true,
    "boldOrderNumber" BOOLEAN NOT NULL DEFAULT true,
    "boldTotal" BOOLEAN NOT NULL DEFAULT true,
    "lineWidth" INTEGER NOT NULL DEFAULT 42,
    "paperWidth" INTEGER NOT NULL DEFAULT 80,
    "characterWidth" INTEGER NOT NULL DEFAULT 48,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "receipt_templates_pkey" PRIMARY KEY ("id")
);
