import { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';

/**
 * CSRF Protection Middleware
 *
 * For API-only routes that use JWT Bearer auth, CSRF is inherently protected
 * because the token is sent in the Authorization header (not in cookies).
 * This middleware:
 * 1. Skips CSRF for requests with Authorization: Bearer header (JWT-authenticated API calls)
 * 2. Skips CSRF for safe methods (GET, HEAD, OPTIONS)
 * 3. Requires a valid X-CSRF-Token header for all other state-changing requests
 *
 * The token is derived from a server-side secret + a per-session token cookie.
 * For pure API consumers (mobile, SPA with Bearer auth), this is a no-op.
 */

const CSRF_SECRET = process.env.CSRF_SECRET || crypto.randomBytes(32).toString('hex');
const CSRF_TOKEN_HEADER = 'x-csrf-token';
const CSRF_COOKIE_NAME = '_csrf';
const CSRF_COOKIE_OPTIONS = {
  httpOnly: false, // Must be readable by client JS for SPA
  sameSite: 'lax' as const,
  secure: process.env.NODE_ENV === 'production',
  path: '/',
};

function generateCsrfToken(): string {
  return crypto.createHmac('sha256', CSRF_SECRET).update(crypto.randomBytes(16).toString('hex')).digest('hex');
}

function verifyCsrfToken(token: string): boolean {
  // Verify that the token was generated by our secret
  // Since we use HMAC, any token we generate will be valid
  // The real protection comes from the cookie-token double-submit pattern
  return typeof token === 'string' && token.length >= 64;
}

/**
 * Sets a CSRF token cookie and returns the token in the response body.
 * Used by browser-based SPAs to get their initial token.
 */
export function csrfTokenHandler(req: Request, res: Response): void {
  const token = generateCsrfToken();
  res.cookie(CSRF_COOKIE_NAME, token, CSRF_COOKIE_OPTIONS);
  res.json({ success: true, data: { csrfToken: token } });
}

/**
 * CSRF protection middleware.
 * Skips for:
 *  - Requests with Authorization: Bearer header (JWT-authenticated)
 *  - Safe HTTP methods (GET, HEAD, OPTIONS)
 *  - Webhook endpoints (verified by signature middleware)
 */
export function csrfProtection(req: Request, res: Response, next: NextFunction): void {
  // Skip for safe methods
  if (['GET', 'HEAD', 'OPTIONS'].includes(req.method)) {
    return next();
  }

  // Skip for JWT Bearer-authenticated requests (API consumers)
  const authHeader = req.headers.authorization;
  if (authHeader?.startsWith('Bearer ')) {
    return next();
  }

  // Skip for print-agent device tokens (header-based, not cookie-based)
  if (authHeader?.startsWith('Device ')) {
    return next();
  }

  // Skip for print-agent pairing (local agent, no browser cookies)
  if (req.path.startsWith('/api/print/agent/')) {
    return next();
  }

  // Skip for webhook endpoints (they use HMAC signature verification instead)
  if (req.path.includes('/webhook')) {
    return next();
  }

  // Skip for Stripe webhook (raw body, no CSRF)
  if (req.path === '/api/payments/webhook') {
    return next();
  }

  // For all other state-changing requests, validate CSRF token
  const csrfToken = req.headers[CSRF_TOKEN_HEADER] as string | undefined;
  const cookieToken = req.cookies?.[CSRF_COOKIE_NAME];

  if (!csrfToken || !cookieToken) {
    res.status(403).json({
      success: false,
      error: 'CSRF token missing. Include X-CSRF-Token header and _csrf cookie.',
    });
    return;
  }

  // Double-submit pattern: token in header must match token in cookie
  if (csrfToken !== cookieToken) {
    res.status(403).json({
      success: false,
      error: 'CSRF token mismatch.',
    });
    return;
  }

  if (!verifyCsrfToken(csrfToken)) {
    res.status(403).json({
      success: false,
      error: 'Invalid CSRF token.',
    });
    return;
  }

  next();
}
